"""Load per-scene sidecar context used by the vision-check supervisor.

Each scene's context lives at::

    <output_root>/<scene_label>/scene_context.json

with this schema::

    {
        "scene_label":         "Act.1-Scene.5-Beach",
        "expected_characters": ["Florence", "Sebastian"],
        "description":         "Florence meets Sebastian on the beach and takes his hand."
    }

The file must be hand-authored before the first render run (or generated by a
future automation issue).  If the file is missing or malformed, the loader
returns a minimal context so the vision check can still run — it just won't
have character names or a scene description to anchor the prompt.
"""

from __future__ import annotations

import json
import os
from typing import Dict, Any


# Keys expected in scene_context.json.
_REQUIRED_KEYS = ("scene_label", "expected_characters", "description")


def load_scene_context(output_root: str, scene_label: str) -> Dict[str, Any]:
    """Load the sidecar JSON for *scene_label* from *output_root*.

    Returns a dict with at least the keys ``scene_label``,
    ``expected_characters``, and ``description``.  If the file is absent or
    cannot be parsed, a minimal fallback dict is returned and a warning is
    printed to stdout (so it appears in the ``=== `` filtered log stream).

    Args:
        output_root: Root directory that contains per-scene output folders.
        scene_label: Label identifying the scene, e.g. ``Act.1-Scene.5-Beach``.

    Returns:
        Dict with keys ``scene_label`` (str), ``expected_characters`` (list of
        str), and ``description`` (str).  Any extra keys in the JSON are passed
        through unchanged.
    """
    sidecar_path = os.path.join(output_root, scene_label, "scene_context.json")

    if not os.path.exists(sidecar_path):
        print(
            f"=== WARNING: scene_context.json not found at {sidecar_path}. "
            "Vision check will run without character/description context."
        )
        return _fallback(scene_label)

    try:
        with open(sidecar_path, "r", encoding="utf-8") as fh:
            data: Dict[str, Any] = json.load(fh)
    except (json.JSONDecodeError, OSError) as exc:
        print(
            f"=== WARNING: Could not parse scene_context.json ({exc}). "
            "Vision check will run without character/description context."
        )
        return _fallback(scene_label)

    # Fill in missing keys with safe defaults.
    for key in _REQUIRED_KEYS:
        if key not in data:
            print(
                f"=== WARNING: scene_context.json is missing key {key!r}. "
                "Using default."
            )

    data.setdefault("scene_label", scene_label)
    data.setdefault("expected_characters", [])
    data.setdefault("description", "(no description provided)")

    return data


def _fallback(scene_label: str) -> Dict[str, Any]:
    """Return a minimal context dict when the sidecar file is unavailable."""
    return {
        "scene_label": scene_label,
        "expected_characters": [],
        "description": "(no description provided)",
    }
